ALTER TABLE servers ADD COLUMN IF NOT EXISTS wg0_public_key TEXT;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS wg0_port INTEGER DEFAULT 51820;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS wg1_public_key TEXT;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS wg1_port INTEGER DEFAULT 51821;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS wg2_public_key TEXT;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS wg2_port INTEGER DEFAULT 51822;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS country_code TEXT;

UPDATE servers SET wg0_public_key = public_key, wg0_port = endpoint_port
WHERE wg0_public_key IS NULL AND public_key IS NOT NULL;
